config/routes.rb
Rails.application.routes.draw do
  # ROOT
  # Root path routes to home page
  root to: "pages#home"

  # GUIDES
  # Place /guides/x routes above resources to override "/guides/:id" show path
  get "/guides/owned", to: "guides#owned", as: "owned_guides"
  get "/guides/dashboard", to: "guides#dashboard", as: "guides_dashboard"
  post "/guides/checkout", to: "guides#checkout", as: "checkout"
  get "/guides/checkout-success", to: "guides#success"
  get "/guides/checkout-cancel", to: "guides#cancel"


  # Use shallow nesting to include :guide_id param in index, create and new Review paths
  resources :guides, shallow: true do
    # REVIEWS
    resources :reviews, except: :show
  end

  # Custom routes for guides
  get "/guides/:id/view", to: "guides#view", as: "view_guide"
  get "/guides/:id/archive", to: "guides#archive", as: "archive_guide"
  get "/guides/:id/restore", to: "guides#restore", as: "restore_guide"

  # CARTS
  # No restful params required as users can only view their own cart
  get "/cart", to: "carts#show", as: "cart"

  # CART GUIDES
  resources :cart_guides, only: [:create, :destroy]
  delete "/cart_guides", to: "cart_guides#destroy_all", as: "clear_cart"

  # USERS
  # Use custom SignupsController to handle registrations (extends devise default to provide added functionality)
  devise_for :users, controllers: { registrations: "signups" }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :guide_tags, dependent: :destroy
  has_many :guides, through: :guide_tags
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <%= link_to "GuideShare", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Library", owned_guides_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Author Dashboard", guides_dashboard_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Browse Guides", guides_path, class: "nav-link" %>
        </li>
        <% unless user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Cart (#{current_user.cart.guides.count})", cart_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
        </ul>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <span class="m-auto"><strong><%= current_user.username %></strong></span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

</nav>

app/views/shared/_stripe.html.erb
<%# Add event listener to purchase button, triggering Stripe checkout %>
<script type="text/javascript">
  function addStripe() {
    // Abort if checkout button not found on page
    if (!document.getElementById('checkout-button')) {
      return;
    }
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('pk_test_51IqT8pBOC4WaG3qlSthuQrdxLLJGwe4JWOzcVZvuC1Cpah4lypBOybTlhe5ZPGwZORLrxUgV6UNm3UmoshBrBu6F00Ra3xwDxj');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function() {
      // If user not signed in, send to sign in page and set the devise post-sign-in redirect page to the current url
      <% if !user_signed_in? %>
        <% session["user_return_to"] = request.url %>
        location = "<%= new_user_session_path %>"
      <% end %>
      // Get CSRF token from meta tag
      const csrfToken = document.querySelector("[name='csrf-token']").content
      // Create a new Checkout Session using the server-side endpoint
      // Post guide ids for use as line items with the request
      fetch('/guides/checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          "X-CSRF-Token": csrfToken,
        },
        body: JSON.stringify({
          'guide_ids': '<%= guide_ids %>',
        }),
      })
      .then(function(response) {
        return response.json();
      })
      .then(function(session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function(result) {
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function(error) {
        console.error('Error:', error);
      });
    });
  };

  document.addEventListener('turbolinks:load', addStripe);

</script>