config/routes.rb
Rails.application.routes.draw do
  # ROOT
  # Root path routes to home page
  root to: "pages#home"

  # GUIDES
  # Place /guides/x routes above resources to override "/guides/:id" show path
  get "/guides/owned", to: "guides#owned", as: "owned_guides"
  get "/guides/dashboard", to: "guides#dashboard", as: "guides_dashboard"
  post "/guides/checkout", to: "guides#checkout", as: "checkout"
  get "/guides/checkout-success", to: "guides#success"
  get "/guides/checkout-cancel", to: "guides#cancel"


  # Use shallow nesting to include :guide_id param in index, create and new Review paths
  resources :guides, shallow: true do
    # REVIEWS
    resources :reviews, except: :show
  end

  # Custom routes for guides
  get "/guides/:id/view", to: "guides#view", as: "view_guide"
  get "/guides/:id/archive", to: "guides#archive", as: "archive_guide"
  get "/guides/:id/restore", to: "guides#restore", as: "restore_guide"

  # CARTS
  # No restful params required as users can only view their own cart
  get "/cart", to: "carts#show", as: "cart"

  # CART GUIDES
  resources :cart_guides, only: [:create, :destroy]
  delete "/cart_guides", to: "cart_guides#destroy_all", as: "clear_cart"

  # USERS
  # Use custom SignupsController to handle registrations (extends devise default to provide added functionality)
  devise_for :users, controllers: { registrations: "signups" }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_guides, dependent: :destroy
  has_many :guides, through: :cart_guides

  # Return the total price of guides in the cart
  def total
    return guides.sum(&:price)
  end

  # Get the username of the user who owns the cart
  def user_name
    return user.username
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart

  # GET /cart
  def show
    # Retrieve all CartGuide instances belonging to the relevant cart (ie. items in the cart). Use "includes" to
    # eager load the guides to which each CartGuide relates. Guide instances will be used to retrieve and display the
    #  title, price and other attributes of the guide in the view.
    @cart_guides = @cart.cart_guides.includes(:guide)

    # Retrieve guide_ids for each guide in the cart, to be passed to Stripe session on checkout.
    @guide_ids = @cart_guides.pluck(:guide_id)
  end

  private

  # Because users can only view their own cart, retrieve the current user's cart. Because user authentication occurs
  # first, no need to verify that current_user is not nil before accessing its cart.
  def set_cart
    @cart = current_user.cart
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_buttons.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-primary me-2 rounded" id="checkout-button">Check Out</button>
  <%= link_back(guides_path, classes="btn btn-secondary rounded me-2") %>
</div>

app/views/carts/_cart_guide.html.erb
<li class="list-group-item d-flex justify-content-between align-items-start mb-2 border rounded">
  <div class="ms-2 me-auto">
    <div class="fw-bold"><%= link_to cart_guide.title, cart_guide.guide %></div>
  </div>
  <span class="badge bg-primary rounded-pill mt-auto mb-auto me-2 fs-6"><%= display_price(cart_guide.guide) %></span>
  <%= button_to "X", cart_guide_path(cart_guide), method: :delete, class: "ms-auto w-auto btn btn-danger" %>
</li>

app/views/carts/show.html.erb
<div class="container mb-4">
  <h1 class="text-center mb-4 mt-3"><%= @cart.user_name %>'s Shopping Cart</h1>
  <div class="container border p-4 mb-4 rounded">
    <div class="row"><h4>Guides in cart</h4></div>
    <%# Display partial for each item in the cart, in an ordered list %>
    <%if @cart_guides.present? %>
      <ol class="list-group list-group-numbered">
        <% @cart_guides.each do |cart_guide| %>
          <%= render partial: "cart_guide", locals: {cart_guide: cart_guide} %>
        <% end %>
      <ol>
    <% else %>
      <p>Your cart is empty!</p>
    <% end %>
    <hr>
    <p class="text-end fs-4 fw-bold me-5">TOTAL: <%= number_to_currency(@cart.total, locale: :en) %></p>
    <div class="d-flex justify-content-end"><%= button_to "Clear Cart", clear_cart_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger rounded me-5" %></div>
    <p>
      <%# Render stripe checkout and clear cart buttons if cart is not empty %>
      <%= render "buttons" unless @cart_guides.empty? %>
      <%# Back link using custom link_back helper %>
      <br>
    </p>
    <%# Include Stripe script tags if cart is not empty (in which case checkout button will be present) %>
    <%= render partial: "shared/stripe", locals: { guide_ids: @guide_ids } unless @cart_guides.empty? %>
  </div>
</div>