config/routes.rb
Rails.application.routes.draw do
  # ROOT
  # Root path routes to home page
  root to: "pages#home"

  # GUIDES
  # Place /guides/x routes above resources to override "/guides/:id" show path
  get "/guides/owned", to: "guides#owned", as: "owned_guides"
  get "/guides/dashboard", to: "guides#dashboard", as: "guides_dashboard"
  post "/guides/checkout", to: "guides#checkout", as: "checkout"
  get "/guides/checkout-success", to: "guides#success"
  get "/guides/checkout-cancel", to: "guides#cancel"


  # Use shallow nesting to include :guide_id param in index, create and new Review paths
  resources :guides, shallow: true do
    # REVIEWS
    resources :reviews, except: :show
  end

  # Custom routes for guides
  get "/guides/:id/view", to: "guides#view", as: "view_guide"
  get "/guides/:id/archive", to: "guides#archive", as: "archive_guide"
  get "/guides/:id/restore", to: "guides#restore", as: "restore_guide"

  # CARTS
  # No restful params required as users can only view their own cart
  get "/cart", to: "carts#show", as: "cart"

  # CART GUIDES
  resources :cart_guides, only: [:create, :destroy]
  delete "/cart_guides", to: "cart_guides#destroy_all", as: "clear_cart"

  # USERS
  # Use custom SignupsController to handle registrations (extends devise default to provide added functionality)
  devise_for :users, controllers: { registrations: "signups" }
end

app/models/guide.rb
class Guide < ApplicationRecord
  # Include "discard" gem functionality to permit "soft deletion" of guides
  # (because "deleted" guides should remain accessible by users who have already purchased them)
  include Discard::Model

  belongs_to :user
  has_one_attached :guide_file
  has_many :user_guides, dependent: :destroy
  has_many :owners, through: :user_guides, source: :user
  has_many :guide_tags, dependent: :destroy
  has_many :tags, through: :guide_tags
  has_many :reviews, dependent: :destroy
  has_many :cart_guides, dependent: :destroy

  # Title must exist, must be unique, and must be between 5 and 120 characters long
  validates :title,
            presence: true,
            uniqueness: true,
            length: {
              minimum: 5,
              maximum: 120,
            }

  # Description must be no more than 1200 characters long
  validates :description, length: { maximum: 1200 }

  # Price must exist, and must be between 0 and 100 (dollars) inclusive
  validates :price,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than: 100,
            }

  # Use active_storage_validations gem to validate attachments. Guide file must be a PDF < 2mb.
  validates :guide_file,
            attached: true,
            content_type: {
              in: 'application/pdf',
              message: 'must be a PDF file',
            },
            size: {
              less_than: 2.megabytes,
              message: 'must be less than 2 megabytes in size',
            }

  # Selects all guides whose titles match a query using case-insensitive wildcard search. Because input from params
  # is used in query via interpolation, manually sanitise with "sanitize_sql_like" helper to prevent SQL injection.
  scope :title_matches_query,
        ->(query) { where('title ILIKE ?', "%#{sanitize_sql_like(query)}%") }

  # Selects all distinct guides whose tags include ANY of a given array of tag ids, by performing an  inner join between
  # Guides and Tags and selecting those entries where the tag id is included in the given array of tag_ids
  scope :has_any_tag,
        ->(tag_ids) { joins(:tags).where('tags.id IN (?)', tag_ids).distinct }

  # Selects all guides whose tags include ALL of a given array of tag ids, by performing an inner join with
  # tags where the tag id is included in the given array of tag ids, grouping the resulting join table entries by
  # Guide ID, and selecting only those where the number of entries for that guide is at least equal to the length of the
  # tag ids array (implying that the Guide with that ID must have an assocation with each tag represented by tag_ids)
  scope :has_all_tags,
        ->(tag_ids) {
          joins(:tags)
            .where('tags.id IN (?)', tag_ids)
            .group('guides.id')
            .having('COUNT(guides.id) >= ?', tag_ids.count)
        }

  # Selects guides published by a given user
  scope :published_by, ->(user) { where(user: user) }

  # Selects guides NOT published by a given user
  scope :not_published_by, ->(user) { where.not(user: user) }

  # Selects the most recently-published guides, up to a limit of num_items. First orders Guides in descending order of
  # creation date, and limits the number of results to the value of num_items.
  scope :recent, ->(num_items) { order(created_at: :desc).limit(num_items) }

  # Get the number of pages in the attached PDF via a Cloudinary API call.
  def get_page_count
    Cloudinary::Api.resource(guide_file.key, pages: true)['pages'].to_i
  end

  # Returns true if the passed user owns a copy of the guide
  def owned_by?(owner)
    return owner && owners.exists?(owner.id)
  end

  # Returns true if the guide was authored by the given user
  def authored_by?(user_obj)
    return user == user_obj
  end

  # Returns true if guide has been purchased by any user
  def has_owners?
    return owners.exists?
  end

  # Returns the number of users who have purchased the guide
  def owners_count
    return owners.count
  end

  # Returns true if the guide has a price of zero, otherwise false
  def free?
    return price.zero?
  end

  # Returns the average rating for a guide, or "Not yet rated" if no reviews exist
  def rating
    return reviews.average(:rating)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :guide_tags, dependent: :destroy
  has_many :guides, through: :guide_tags
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show checkout]
  before_action :set_guide,
                only: %i[show edit update destroy view archive restore]

  # GET /guides
  def index
    # Retrieve all Tags, used in checkboxes in search form partial
    @tags = Tag.all

    # Retrieve only guides which are "kept" (ie. have not been archived using the Discard gem) and not created by
    # the current user. Eager load user, tags and guide_tags associations, to avoid unnecessary "N+1" queries in the view.
    # Use ".includes" if possible, but use ".preload" instead if filtering for guides that match all selected tags (because
    # .includes causes a grouping error if used with the queries in the "Guide.has_all_tags" scope)
    @guides =
      if params[:search].present? && params[:search][:tags_match].to_i == 1
        Guide.kept.not_published_by(current_user).preload(%i[user tags guide_tags])
      else
        Guide.kept.not_published_by(current_user).includes(%i[user tags guide_tags])
      end

    # If no search params are present, return and render the view. Code below executes only if search params are present.
    return unless params[:search].present?

    # Store the searchbar query
    @query = params[:search][:query]

    # Store array of tag IDs selected for filtering results. First remove empty strings (first element will be an
    # empty string due to Rails query params parsing behaviour) and cast to integers.
    @tag_ids = (params[:search][:tags] - ['']).map(&:to_i)

    # Store the selection for tag filtering (whether to match any or all)
    @tags_match = (params[:search][:tags_match]).to_i

    # Filter guides based on search query, selected tags, and filter type
    @guides = apply_search_filter(@guides, @query, @tag_ids, @tags_match)
  end

  # GET /guides/dashboard
  def dashboard
    # Retrieve all guides of which the current user is the author, using "published_by" custom model scope.
    # Use "includes" to eager load user, guide_tags and tags associations whose attributes are used in the view,
    # to avoid unnecessary "N+1" queries.
    @guides =
      Guide.includes(:user, :guide_tags, :tags).published_by(current_user)
  end

  # GET /guides/:id
  # Displays the listing for a guide (but not the contents of the PDF file attached to the guide)
  def show
    # If user not authorised, redirect to guides index page and alert error.
    authorize_guide(
      @guide,
      'Guide does not exist or you are not authorised to view it',
      guides_path,
    )

    # Use Review model's custom "recent" scope to retrieve the most recently-created 3 reviews
    # of the relevant guide. Use "includes" to eager-load the user to which the review belongs, used
    # in the view to display the author's name.
    @reviews = @guide.reviews.includes(:user).recent(3)
  end

  # GET/guides/:id/view
  # Display the content of the PDF file attached to a Guide
  def view
    # Check if user is authorized to view the guide. If not, redirect with an alert message.
    authorize_guide(@guide, 'You must purchase this guide in order to view it')
    # Retrieve the user who created the guide, used to display the author's name in the view
    @author = @guide.user
    # Get number of pages in guide file for display. Makes a Cloudinary API call.
    @page_count = @guide.get_page_count
  end

  # GET /guides/new
  def new
    # Create an empty guide object to extract attributes for new guide form
    @guide = Guide.new
  end

  # POST /guides
  def create
    # Construct a new guide belonging to the current user using strong params from form data
    @guide = current_user.guides.new(guide_params)

    # Attempt to save the new guide.
    if @guide.save
      # If successful, redirect to the guide's show page and notify success.
      redirect_to @guide,
                  notice: "Guide \"#{@guide.title}\" was successfully created."
    else
      # If save fails, re-render the "new guide" form. Errors will be displayed to the user in the view.
      render :new, status: :unprocessable_entity
    end
  end

  # GET /guides/:id/edit
  def edit
    # If user is not authorised to edit the guide, redirect to the guide's show page and alert the error
    authorize_guide(@guide, 'Only the author may edit this guide')
  end

  # PUT/PATCH /guides/:id
  def update
    # If user is not authorised to update the guide, redirect to the guide's show page and alert the error.
    # To prevent multiple redirect/render error, return if authorisation fails.
    return unless authorize_guide(@guide, 'Only the author may edit this guide')

    # Attempt to update the guide using strong params from form data.
    if @guide.update(guide_params)
      # Redirect to the guides' show page and notify if update successful
      redirect_to @guide,
                  notice: "Guide \"#{@guide.title}\" was successfully updated."
    else
      # Re-render "edit" page with error messages if update fails.
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /guides/:id
  def destroy
    # If user is not authorised to delete the guide, redirect to the guide's show page and alert the error.
    # To prevent multiple redirect/render error, return if authorisation fails.
    return unless authorize_guide(@guide, 'Only the author may delete this guide')

    # If any users have already purchased the guide, redirect to the Guides index page and notify user
    # that the guide cannot be deleted, only archived.
    if @guide.has_owners?
      redirect_to guides_path,
                  alert:
                    'Guide could not be deleted because it has been purchased by one or more users. Try archiving it instead.'
    # Otherwise, allow guide to be deleted, redirect to Guides index and notify success.
    else
      @guide.destroy
      redirect_to guides_path, notice: 'Guide listing was successfully deleted.'
    end
  end

  # GET /guides/:id/archive
  def archive
    # If user is not authorised to archive the guide, redirect to the guide's show page and alert the error.
    # To prevent multiple redirect/render error, return if authorisation fails.
    return unless authorize_guide(@guide, 'Only the author may archive this guide')

    # Archive guide by "soft deleting" using the Discard gem, making it accessible only to the owner and
    # users who have already purchased it.
    @guide.discard

    # Dependents are not destroyed when discarding, so manually remove discarded guides from all users' shopping carts
    CartGuide.for_guide(@guide).destroy_all
    redirect_to guide_path(@guide),
                notice:
                  'Guide listing was successfully archived. NOTE: Any users who already purchased the guide will retain access to it.'
  end

  # GET /guides/:id/restore
  def restore
    unless authorize_guide(
             @guide,
             'Guide does not exist or you are not authorised to restore it from the archive',
           )
      return
    end

    # Restore archived guide by "undiscarding" with Discard gem method, making it accessible to all users again
    @guide.undiscard
    redirect_to guide_path(@guide),
                notice: 'Guide listing was successfully restored.'
  end

  # POST /guides/checkout
  def checkout
    # Retrieve guide ids from params. If received as JSON (such as from Stripe checkout button),
    # first parse array of guide ids from JSON and map each id to an integer.
    @guide_ids =
      if params[:guide_ids].is_a?(String)
        JSON.parse(params[:guide_ids]).map(&:to_i)
      else
        params[:guide_ids]
      end

    # Retrieve guides whose ids are included in the array of guide_ids received via params
    @guides = Guide.where(id: @guide_ids)

    # Prevent initiating purchase if any guide is already owned by the user, or is archived
    return if @guides.any? { |guide| guide.owned_by?(current_user) || guide.discarded? }

    # "Free" param will be true only if the user is attempting to add a single free guide to their library. If so,
    # add the guide to the user's library directly, redirect to the user's library with a success notice, and return.
    if params[:free]
      add_to_library(@guides)
      redirect_to owned_guides_path, notice: 'Guide was added to your library!'
      return
    end

    # If not acquiring a free guide, initiate Stripe checkout.
    # Set API key to access Stripe API
    Stripe.api_key = ENV['STRIPE_API_KEY']

    # Generates an array of line items in Stripe's required format
    @line_items = generate_line_items(@guides)

    # Create a Stripe session
    session =
      Stripe::Checkout::Session.create(
        {
          payment_method_types: ['card'],
          line_items: @line_items,
          mode: 'payment',
          # These routes handle successful or canceled checkout
          success_url:
            "#{request.base_url}/guides/checkout-success?session_id={CHECKOUT_SESSION_ID}",
          cancel_url: "#{request.base_url}/guides/checkout-cancel",
        },
      )

    # Send Stripe session data as JSON
    render json: session
  end

  # GET /guides/checkout-success
  # User is redirected here when Stripe checkout succeeds
  def success
    # Set key to access Stripe API
    Stripe.api_key = ENV['STRIPE_API_KEY']

    # Stripe API call to retrieve information about line items included in purchase
    @line_items_data =
      Stripe::Checkout::Session.list_line_items(params[:session_id])['data']

    # Extract guide IDs from Stripe session data (sent when clicking purchase/checkout button) and map them to @guide_ids
    @guide_ids =
      @line_items_data.map do |item|
        Stripe::Product.retrieve(item['price']['product'])['metadata']['id']
      end

    # Retrieve only those guides whose ids are included in the line items data
    @guides = Guide.where(id: @guide_ids)

    # Adds each purchased guide to the user's owned guides

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_add_to_lib_script.html.erb
<script>
  <% if !user_signed_in? %>
    // Anonymous IIFE which executes on page load if user is not signed in
    (() => {
      // Abort if add to library button not found on page
      if (!document.getElementById('add-to-lib')) {
        return;
      }
      // Get a reference to the Add to Library button
      addToLib = document.getElementById('add-to-lib');
      // Change its type to "button" to prevent it from submitting the hidden form generated by button_to
      addToLib.setAttribute("type", "button");
      // Instead, add an event listener that sends user to the sign-in page after setting the devise post-sign-in 
      // redirect location to the current page
      addToLib.addEventListener("click", () => {
          <% session["user_return_to"] = request.url %>
          location = "<%= new_user_session_path %>"
      });
    })();
  <% end %>
</script>

app/views/guides/_card.html.erb
<%# Shade background if guide is archived %>
<div class="card mb-3 ms-1 me-1 flex-grow-1 <%= "archived" if guide.discarded? %>" style="width: 18rem;">
  <div class="card-body">
    <h4 class="card-title">
      <%= link_to guide.title, guide %>
      <% if guide.discarded? %>
        <span class="text-muted fs-4"> (Archived)</span>
      <% end %>
    </h4>
    <%# Display if current user already owns the guide. Otherwise, display its price. %>
    <% if guide.owned_by?(user_or_guest) %>
      <h5 class="card-subtitle mb-2 text-muted">Owned</h5>
    <% else %>
      <h5 class="card-subtitle mb-2 text-muted"><%= display_price(guide) %></h5>
    <% end %>
    <%# Display author and rating %>
    <h5 class="card-subtitle mb-2 text-muted">Created by: <%= display_author(guide) %></h5>
    <h5 class="card-subtitle mb-2 text-muted">Rating: <%= display_rating(guide.rating) %></h5>
    <%# If user is the author, display how many others have purchased the guide %>
    <% if guide.authored_by?(user_or_guest) %>
      <p class="text-muted"><%= display_owners_count(guide) %></p>
    <% end %>
    <%# Display tags and description %>
    <p class="text-muted">Tags: <%= display_guide_tags(guide) %></p>
    <p class="card-text"><%= truncate(description_text(guide), length: 250) %></p>
    <%# Render links to view/modify guide. Use full path, as this partial is sometimes used from outside the Guides view folder. %>
    <%= render partial: "guides/links", locals: {guide: guide} %>
  </div>
</div>

app/views/guides/_carousel_controls.html.erb
<div>
  <button class="carousel-control-prev" type="button" data-bs-target="#guideCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
</div>
<div>
  <button class="carousel-control-next" type="button" data-bs-target="#guideCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/guides/_carousel_img.html.erb
<div class='<%= page_num == 1 ? "carousel-item active" : "carousel-item" %>'>
  <span class="d-flex justify-content-center fs-3 fw-bold"><%= "Page #{page_num} of #{@page_count}" %></span>
  <%# Retrieve image of page from Cloudinary %>
  <%= cl_image_tag "#{@guide.guide_file.key}.png", cloud_name: "chriskamp", page: page_num, class: "d-block img-fluid ms-4" %>
</div>

app/views/guides/_form.html.erb
<div class="container rounded border p-2">
  <%# Form created using simple form gem with bootstrap styles integration. %>
  <%# Maps non-text fields to relevant bootstrap classes with wrapper_mappings. %>
  <h4 class="mb-4"><%= subheading %></h4>
  <%= simple_form_for @guide, wrapper: :horizontal_form, wrapper_mappings: {
    file: :horizontal_file, check_boxes: :horizontal_collection_inline
  } do |f| %>
    <%= f.error_notification %>
  
    <div class="form-inputs">
      <%# Simple form automatically determines input type based on the specified attribute, and generates label and input field. %>
      <%= f.input :title,
                  required: true,
                  autofocus: true, wrapper_html: {class: "mt-5 mb-5"} %>
      <%= f.input :description, wrapper_html: {class: "mb-5"} %>
      <%= f.input :price, label: "Price ($)", hint: "Enter 0 if the guide should be free", wrapper_html: {class: "mb-5"}, input_html: {step: 0.01} %>
      <%# Create checkboxes for each tag in @guide.tags %>
      <%= f.association :tags, as: :check_boxes, wrapper_html: {class: "mb-5"} %>
      <%= f.input :guide_file, label: "Guide file (PDF)", wrapper_html: {class: "mb-5"}, hint: (subheading == "Edit" ? "Leave empty if you don't want to replace the guide file" : "") %>
    </div>
  
    <div class="form-actions">
      <%= f.button :submit, class: "btn-primary"%>
    </div>
  <% end %>
</div>

app/views/guides/_links.html.erb
<%# Provide link to read guide, if user is authorised to do so %>
<% if policy(guide).view? %>
  <%= link_to "Read Now", view_guide_path(guide), class: "btn btn-primary mt-2" %>
<% end %>
<%# If user owns the guide, provide link to post a new review, or to edit existing review if one already posted %>
<% if guide.owned_by?(user_or_guest) %>
  <% unless current_user.reviewed?(guide) %>
    <%= link_to("Review", new_guide_review_path(guide_id: guide.id), class: "btn btn-primary mt-2") %>
  <% else %>
    <%= link_to("Edit Review", edit_review_path(current_user.review(guide)), class: "btn btn-primary mt-2") %>
  <% end %>
<% end %>
<%# Provide link to edit guide if user is authorised to do so %>
<% if policy(guide).edit? %>
  <%= link_to "Edit", edit_guide_path(guide), class: "btn btn-primary mt-2" %>
<% end %>
<%# Provide button to delete guide if user is authorised to do so %>
<div class="button-group">
  <% if policy(guide).destroy? %>
    <%# Delete button is disabled with an explanatory tooltip if the guide has already been purchased by one or more users %>
    <% if guide.has_owners? %>
      <div class="d-inline-block" data-toggle="tooltip" data-placement="bottom" title="Guides that have been purchased by users can only be archived, not deleted.">
        <%= button_to "Delete", guide_path(guide), method: :delete, class: "btn btn-danger disabled d-inline-block w-auto mt-2" %>
      </div>
    <%# Otherwise, delete button is active and has a confirmation prompt %>
    <% else %>
      <%= button_to "Delete", guide_path(guide), method: :delete, class: "btn btn-danger mt-2", data: {confirm: "Are you sure?"}, form: {class: "d-inline-block"} %>
    <% end %>
  <% end %>
  <%# Provide button to archive guide if user is authorised to do so %>
  <% if policy(guide).archive? %>
    <%= button_to "Archive", archive_guide_path(guide), method: :get, class: "btn btn-warning mt-2", data: {confirm: "Are you sure?"}, form: {class: "d-inline-block"} %>
  <%# Provide button to restore archived guide if user is authorised to do so %>
  <% elsif policy(guide).restore? %>
    <%= button_to "Restore", restore_guide_path(guide), method: :get, class: "btn btn-warning mt-2", data: {confirm: "Are you sure?"}, form: {class: "d-inline-block"} %>
  <% end %>
</div>

app/views/guides/_search.html.erb
<div class="container mb-5 p-3 rounded border">
  <div class="row">
    <h4>Search or filter guides</h4>
  </div>
  <%= simple_form_for :search, url: guides_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :query, input_html: {value: ""}, label: "Search by title", required: false %>
    <%= f.input :tags, as: :check_boxes, collection: @tags, label_method: :name, value_method: :id, input_html: {value: ""}, label: "Select tags", required: false, wrapper: :horizontal_collection_inline %>
    <%= f.input :tags_match, label: "Match tags", as: :radio_buttons, collection: [[0, "Any"], [1, "All"]], checked: 0, label_method: :second, value_method: :first, prompt: "Match tags:", required: false, wrapper: :horizontal_collection_inline %>
    <br>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/guides/dashboard.html.erb
<div class="container">
  <h1 class="mb-4 mt-3 text-center">Author Dashboard</h1>
  <div class="container p-4 mb-4 rounded m-auto" style="width: 12rem;">
    <div class="row">
      <%= link_to "Create a guide", new_guide_path, class: "btn btn-primary m-auto w-auto p-3" %>
    </div>
  </div>
  <%# User's published guides %>
  <div class="container border p-4 rounded mb-4">
      <div class="row">
        <h4 class="mb-4">Guides you have published</h4>
      </div>
    <% if user_or_guest.published_any_guides? %>
      <div class="row">
        <%= render partial: "guides/guides", locals: { guides: @guides } %>
      </div>
      <%= paginate @guides %>
    <% else %>
      <div class="row">
        <p>You haven't published any guides yet!</p>
      </div>
    <% end %>
  </div>
</div>

app/views/guides/edit.html.erb
<div class="container">
  <h1 class="text-center mb-4 mt-3">Edit <%= @guide.title %></h1>
  <%= render partial: "form", locals: { subheading: "Edit" } %>
</div>

app/views/guides/index.html.erb
<div class="container">
  <h1 class="mb-4 mt-3 text-center">Guides</h1>
  <%= render "search" %>
  <div class="container border p-4 rounded mb-4">
    <div class="row">
        <h4 class="mb-4">Guides</h4>
      </div>
    <% unless @guides.empty? %>
      <div class="row">
        <%= render partial: "guides/guides", locals: { guides: @guides } %>
      </div>
      <%= paginate @guides %>
    <% else %>
      <div class="row">
        <p>No guides have been published, or no guides match your search criteria.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/guides/new.html.erb
<div class="container">
  <h1 class="text-center mb-4 mt-3">New Guide</h1>
  <%= render partial: "form", locals: { subheading: "New" } %>
</div>

app/views/guides/show.html.erb
<%# Shade background if guide is archived %>
<div class="container">
  <h1 class="text-center mb-4 mt-3"><%= @guide.title %><%= " (Archived)" if @guide.discarded? %></h1>
    <%# Display if current user already owns the guide. Otherwise, display its price. %>
  <div class="container rounded border mb-4 p-4 <%= "archived" if @guide.discarded? %>">
    <h4 class="mb-4">Details</h4>
    <% if @guide.owned_by?(user_or_guest) %>
      <h4 class="text-muted">Owned</h4>
    <% else %>
      <h4 class="text-muted">Price: <%= display_price(@guide) %></h4>
    <% end %>
    <%# Display author and rating %>
    <h5 class="text-muted">Created by: <%= display_author(@guide) %></h5>
    <h5 class="card-subtitle mb-2 text-muted">Rating: <%= display_rating(@guide.rating) %></h5>
    <%# If user is the author, display how many others have purchased the guide %>
    <% if @guide.authored_by?(user_or_guest) %>
      <p class="text-muted"><%= display_owners_count(@guide) %></p>
    <% end %>
    <%# Display tags and description %>
    <p class="text-muted">Tags: <%= display_guide_tags(@guide) %></p>
    <hr>
    <p><%= description_text(@guide) %></p>
    <%# If guide not already viewable by user, display buttons to add to library, buy now and/or add to cart %>
    <p>
      <% unless policy(@guide).view? %>
        <%# Render "Add to library" button if guide is free %>
        <% if @guide.free? %>
          <%= button_to "Add to Library", checkout_path, params: { free: true, guide_ids: [@guide.id] }, id: "add-to-lib", class: "btn btn-primary d-inline-block", form: { class: "d-inline-block" } %>
        <%# If guide is not free, add to cart and buy now buttons may be rendered %>
        <% else %>
          <%# Display Add To Cart if not already in cart %>
          <% unless user_or_guest.in_cart?(@guide) %>
            <%# Creates form with hidden fields for "CartGuide". Posts to cart_guides#create, effectively adding a guide to user's cart. %>
            <%= button_to "Add to cart", cart_guides_path, class: "btn btn-primary d-inline-block", form: { class: "d-inline-block" }, params: { cart_guide: { cart_id: user_or_guest.cart.id, guide_id: @guide.id } } %>
          <% end %>
          <%# Display stripe checkout button %>
          <button id="checkout-button" class="btn btn-primary d-inline-block">Buy Now</button>
        <% end %>
      <% end %>
    </p>
    <%# Render links to view/modify guide %>
    <%= render partial: "links", locals: { guide: @guide } %>
  </div>
  <%# Display reviews for the guide %>
  <div class="container border rounded mb-4 p-4">
    <h4>Recent Reviews</h4>
    <hr>
    <% if @reviews.present? %>
      <ul class="list-group mb-2">
        <% @reviews.each do |review| %>
          <%= render partial: "reviews/review", locals: {review: review} %>
        <% end %>
      </ul>
      <%= link_to "See all reviews", guide_reviews_path(@guide), class: "btn btn-primary d-inline-block", form: {class: "d-inline-block"} %>
    <% else %>
      <p>No reviews have been posted yet!</p>
    <% end %>
    <%= link_to "Back to guides", guides_path, class: "btn btn-primary d-inline-block", form: {class: "d-inline-block"} %>
    <%# Include Stripe script tags if guide is not viewable or free (in which case Buy Now button will be present) %>
    <%= render(partial: "shared/stripe", locals: {guide_ids: [@guide.id]}) unless (policy(@guide).view? || @guide.free?) %>
    <%# Include script which causes the "Add to Library" button to redirect to sign-in page if user is not signed in %>
    <%= render "add_to_lib_script" %>
  </div>
</div>